version: 1
build:
  main: ./cmd/mund
  proto:
    path: ""
    third_party_paths: []
accounts:
- name: alice
  coins:
  - 2000000000utmun
  mnemonic: alarm robust diet dinosaur honey pencil dial wall scene strategy hint
    predict bleak physical ancient creek insane limb boring scan eager erode behave
    vehicle
- name: bob
  coins:
  - 10000utmun
  mnemonic: economy ticket horror harbor draw educate vehicle fly hen crystal album
    exist mechanic creek ugly economy say category lunar much sound during inmate
    coyote
- name: tom
  coins:
  - 1000000000000utmun
  mnemonic: orphan cradle clarify priority jeans light hold country bright flight
    tail position various bunker later scale nose edge suggest fit direct lock immense
    tumble
- name: jerry
  coins:
  - 100000000000000utmun
  mnemonic: degree tissue code business hair agree fruit print bargain tissue fuel
    small neutral word prefer glimpse fiscal mention lawn royal balance tray jazz
    faculty
faucet:
  name: bob
  coins:
  - 100000utmun
  host: 0.0.0.0:4500
client:
  typescript:
    path: ts-client
  vuex:
    path: vue/src/store
  hooks:
    path: react/src/hooks
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    staking:
      params:
        bond_denom: utmun
validators:
- name: alice
  bonded: 100000000utmun
- name: bob
  bonded: 1000000000utmun
